version: '3'

services:
  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - network-frontend
      - network-backend
  
  backend:
    build: ./backend
    depends_on:
      - postgres
    expose:
      - "8081"
    restart: always 
    networks:
      - network-backend
      - network-frontend

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "4000:4000"
      - "24678:24678"
    expose:
      - "3001"
    volumes:
      - node_modules:/usr/src/nuxt-app/node_modules/
    restart: always 
    networks:
      - network-frontend
  
  postgres:
    image: postgres:16.0-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: merrychristmas
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always 
    networks:
      - network-backend

networks:
  network-backend:
  network-frontend:

volumes:
  postgres:
  node_modules:
